<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="properties1">

<!-- Properties file for Robco19M robot -->
<!-- Created by Stefan -->
<!-- Service Robotics Group Bulgaria - Version 1.0 from Oct. 1th, 2018. -->


<!-- ####### generic constants ##### -->
  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.14159265358979323846264338327950288419716" />
  <!--<xacro:property name="M_PI" value="3.1415926535897931" />-->
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="DEGREES_90" value="1.570796327" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />
  <xacro:property name="SCALE_in_m" value="0.0254"/> <!--inches to meters-->
  <xacro:property name="SCALE_mm_m" value="0.001"/> <!--milimeters to meters-->
  <xacro:property name="kgcm_to_nm" value="0.0980665" />
   <!-- robot constants -->


 
  <!-- base_link - Base Plate/Deck Cylinder base   -->
  <xacro:property name="base_from_base_frame_Z_offset" value="0.10"/>
  <xacro:property name="base_height" value="${0.375*SCALE_in_m}" /> 
  <xacro:property name="base_radius" value="${17.75*SCALE_in_m/2}" /> 
  <!-- in kg weight with the battery holder plate bellow -->
  <xacro:property name="base_mass" value="1.75" /> 
  
   <!-- distance between the robot origin and the bottom of the base plate along the z axis (robot up) -->
  <xacro:property name="BASE_PLATE_FROM_BASE_FRAME_Z_OFFSET" value="${0.10+(base_height/2)}" /> <!-- meters -->

 <!-- second_deck - Base Plate/Deck Cylinder base   -->
  <xacro:property name="second_deck_from_base_link_Z_offset" value="${0.145+(second_deck_height/2)}"/>
  <xacro:property name="second_deck_height" value="${0.375*SCALE_in_m}" /> 
  <xacro:property name="second_deck_radius" value="${17.75*SCALE_in_m/2}" /> 
  <xacro:property name="second_deck_mass" value="1.5" />   <!-- in kg -->

  <!-- third_deck - Base Plate/Deck Cylinder base   -->
  <xacro:property name="third_deck_from_second_deck_Z_offset" value="${0.156+(third_deck_height/2)}"/>
  <xacro:property name="third_deck_height" value="${0.375*SCALE_in_m}" /> 
  <xacro:property name="third_deck_radius" value="${17.75*SCALE_in_m/2}" /> 
  <xacro:property name="third_deck_mass" value="1.5" />   <!-- in kg -->


 <xacro:macro name="robco_kinect_support_plate" params="parent lenght width height x_loc y_loc z_loc">
    <joint name="standoff_kinect_support_plate_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc+lenght/2}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_kinect_support_plate_link" />
    </joint>

    <link name="standoff_kinect_support_plate_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
        <box size="${lenght} ${width} ${height}"/>
          <!--<mesh filename="package://robot_description/meshes/68-02421-8000-RA_Eddiebot_F-F_Standoff.dae" scale="${SCALE_mm_m} ${SCALE_mm_m} ${SCALE_mm_m}"/>-->
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
        <box size="${lenght} ${width} ${height}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>




</robot>