<?xml version='1.0'?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="robco19m_base">

<!-- Robco 19M base description -->
<!-- Created by Stefan -->
<!-- Service Robotics Group Bulgaria - Version 2.0 from Oct. 1th, 2018. -->


<xacro:macro name="r19m_base">

 

  <!-- BASE FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
             navigation stack depends on this frame -->
             
  <!--<link name="base_footprint">
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
             <box size="0.001 0.001 0.001" />
          </geometry>
      </visual>

      <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.001 0.001 0.001" />
         </geometry>
     </collision>
  </link>-->

     <!--NB: While you would think this would make it go up, it is oddly reversed.
      This moves the joint to 0,0,0 where we want it for rviz, etc. -->
     <!-- origin xyz="0 0 0.130" rpy="0 0 0" / -->
     <!--<origin xyz="0 0 0.18" rpy="0 0 0" />-->

  <!--<joint name="base_footprint_joint" type="fixed">  
     <origin xyz="0 0 ${base_Z_offset/10000}" rpy="0 0 0" />
     
     <parent link="base_footprint"/>
     <child link="base_link" />
  </joint>-->

<!--#### CHASSIS ##############################################################################-->
 
<!--
     base_link is defined as a point in the middle of the height of the metal base platform shell, in the crossing 
     between the imaginery line between the middle of the front left wheel and right rear wheel and 
     the imaginery line between front right wheel and rear left wheel (all this, looking from the top, 
     above the robot). 
  -->
<link name='base_link'>
    <!--<pose>0 0 0.1 0 0 0</pose>-->

    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 ${base_Z_offset}" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <!--<collision name='collision'>-->
    <collision>
      <origin xyz="0 0 ${base_Z_offset}" rpy=" 0 0 0"/>
      <geometry>
       <box size="${base_width} ${base_height} ${base_lenght}"/>
      </geometry>
    </collision>

    <!--<visual name='chassis_visual'>-->
    <visual>    
      <origin xyz="0 0 ${base_Z_offset}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${base_lenght} ${base_width} ${base_height}"/>
      </geometry>
      <material name="yellow"/>
    </visual>    
</link>
<!--#### END CHASSIS ##############################################################################-->


<!--#### WHEELS ##############################################################################-->
<xacro:mecanum_wheel name="left_front_wheel" x="0" y="0" z="0" roll="0" pitch="${DEGREES_90}" yaw="${DEGREES_90}" color="silver"/>
<xacro:mecanum_wheel name="left_rear_wheel" x="0" y="0" z="0" roll="0" pitch="${DEGREES_90}" yaw="${DEGREES_90}" color="silver"/>
<xacro:mecanum_wheel name="right_front_wheel" x="0" y="0" z="0" roll="0" pitch="${DEGREES_90}" yaw="${DEGREES_90}" color="silver"/>
<xacro:mecanum_wheel name="right_rear_wheel" x="0" y="0" z="0" roll="0" pitch="${DEGREES_90}" yaw="${DEGREES_90}" color="silver"/>


  <joint type="continuous" name="left_front_wheel_hinge">
    <origin xyz="${wheel_mount_point_X_offset} ${wheel_mount_point_Y_offset} ${wheel_mount_point_Z_offset}" rpy="0 0 0"/>
    <child link="left_front_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <joint type="continuous" name="left_rear_wheel_hinge">
    <origin xyz="-${wheel_mount_point_X_offset} ${wheel_mount_point_Y_offset} ${wheel_mount_point_Z_offset}" rpy="0 0 0"/>
    <child link="left_rear_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <joint type="continuous" name="right_front_wheel_hinge">
    <origin xyz="${wheel_mount_point_X_offset} -${wheel_mount_point_Y_offset} ${wheel_mount_point_Z_offset}" rpy="0 0 0"/>
    <child link="right_front_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <joint type="continuous" name="right_rear_wheel_hinge">
    <origin xyz="-${wheel_mount_point_X_offset} -${wheel_mount_point_Y_offset} ${wheel_mount_point_Z_offset}" rpy="0 0 0"/>
    <child link="right_rear_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>
  <!--##### END WHEELS #############################################################################-->
 

  <!--##### ARM MOUNT JOINT #############################################################################-->
  <joint name="Arm_mount_joint" type="fixed">
    <parent link="base_link"/> 
    <child link="arm_base_link"/>
    <origin xyz="0 0 0.1" rpy="0 0 0" />
  </joint>
  <!--##### END ARM MOUNT JOINT #############################################################################-->

  <!--##### RPlidar A2 MOUNT JOINT #############################################################################-->
  <joint name="Rplidar_A2_mount_joint" type="fixed">
    <parent link="base_link"/> 
    <child link="rplidar"/>
    <origin xyz="0.13 0 0.08" rpy="0 0 0" />
  </joint>


    <!-- RP_LIDAR -->
  <link name="rplidar">
    <inertial>
      <mass value="1.8362923" />
      <origin xyz="0.0000000 0.0000000 -0.01040000" rpy="0 0 0"/>
      <inertia ixx="0.0009124" ixy="0.0" ixz="0.0"
               iyy="0.0009124" iyz="0.0" 
               izz="0.0013154" />
    </inertial>
    <visual>
      <origin xyz="0 -0.027 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://robot_description/meshes/rplidar_a2/RPlidar_A2.stl.obj" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <!--<origin xyz="0 0 0" rpy="0 0 0"/>-->
      <geometry>
        <mesh filename="package://robot_description/meshes/rplidar_a2/RPlidar_A2.stl.obj" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <!--##### END RPlidar A2 MOUNT JOINT #############################################################################-->  
  
  <!--##################################################################################-->
  
  
 </xacro:macro> 
 

</robot>
